# Generated by Django 5.1.4 on 2025-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'Historiacen',
                'managed': False,
            },
        ),
    ]
