# Generated by Django 5.1.4 on 2025-01-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaProduktow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategoria', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Listaproduktow',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BazaSklepow.listaproduktow')),
                ('przekatna_cal', models.IntegerField()),
                ('odswiezanie_Hz', models.IntegerField()),
                ('rozdzielczosc', models.BigIntegerField()),
                ('typ_wyswietlacza', models.CharField(max_length=255)),
                ('glosniki', models.BooleanField()),
                ('proporcje_ekranu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Monitor',
            },
        ),
        migrations.CreateModel(
            name='Procesor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BazaSklepow.listaproduktow')),
                ('liczba_rdzeni', models.BigIntegerField()),
                ('taktowanie', models.BigIntegerField()),
                ('rodzaj_gniazda', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Procesor',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BazaSklepow.listaproduktow')),
                ('typ_pamieci', models.CharField(max_length=255)),
                ('pojemnosc_GB', models.IntegerField()),
                ('taktowanie_MHz', models.BigIntegerField()),
            ],
            options={
                'db_table': 'RAM',
            },
        ),
        migrations.CreateModel(
            name='Telewizor',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BazaSklepow.listaproduktow')),
                ('przekatna_cal', models.IntegerField()),
                ('typ_wyswietlacza', models.CharField(max_length=255)),
                ('rozdzielczosc_xK', models.BigIntegerField()),
                ('smart_TV', models.BooleanField()),
            ],
            options={
                'db_table': 'Telwizor',
            },
        ),
        migrations.CreateModel(
            name='ListaSklepow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('id_produktu', models.ForeignKey(db_column='id_produktu', on_delete=django.db.models.deletion.CASCADE, to='BazaSklepow.listaproduktow')),
            ],
            options={
                'db_table': 'Listasklepow',
            },
        ),
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BazaSklepow.listaproduktow')),
                ('pojemnosc_dysku', models.IntegerField()),
                ('procesor', models.ForeignKey(db_column='procesor', on_delete=django.db.models.deletion.CASCADE, to='BazaSklepow.procesor')),
                ('pamiec_RAM', models.ForeignKey(db_column='pamiec_RAM', on_delete=django.db.models.deletion.CASCADE, to='BazaSklepow.ram')),
            ],
            options={
                'db_table': 'Komputer',
            },
        ),
        migrations.CreateModel(
            name='ListaOpinii',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('opinia', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('id_produktu', models.ForeignKey(db_column='id_produktu', on_delete=django.db.models.deletion.CASCADE, to='BazaSklepow.listaproduktow')),
            ],
            options={
                'unique_together': {('id',)},
            },
        ),
        migrations.CreateModel(
            name='HistoriaCen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
                ('id_sklepu_z_danym_produktem', models.ForeignKey(db_column='id_sklepu_z_danym_produktem', on_delete=django.db.models.deletion.CASCADE, to='BazaSklepow.listasklepow')),
            ],
            options={
                'unique_together': {('id',)},
            },
        ),
    ]
