# Generated by Django 5.1.4 on 2025-01-01 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historiacen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'historiacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listaproduktow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kategoria', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listaproduktow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listaopinii',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('opinia', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'listaopinii',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listasklepow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listasklepow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.listaproduktow')),
                ('pojemnosc_dysku', models.IntegerField()),
            ],
            options={
                'db_table': 'komputer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.listaproduktow')),
                ('przekatna_cal_field', models.IntegerField(db_column='przekatna_(cal)')),
                ('odswiezanie_hz_field', models.IntegerField(db_column='odswiezanie_(Hz)')),
                ('rozdzielczoťŠ', models.BigIntegerField()),
                ('typ_wyswietlacza', models.CharField(max_length=255)),
                ('glosniki_field', models.IntegerField(db_column='glosniki_')),
                ('proporcje_ekranu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'monitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procesor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.listaproduktow')),
                ('liczba_rdzeni', models.BigIntegerField()),
                ('taktowanie', models.BigIntegerField()),
                ('rodzaj_gniazda', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'procesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.listaproduktow')),
                ('typ_pamieci', models.CharField(max_length=255)),
                ('pojemnosc_gb_field', models.IntegerField(db_column='pojemnosc_(GB)')),
                ('taktowanie_mhz_field', models.BigIntegerField(db_column='taktowanie_(MHz)')),
            ],
            options={
                'db_table': 'ram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telewizor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.listaproduktow')),
                ('przekatna_cal_field', models.IntegerField(db_column='przekatna_(cal)')),
                ('typ_wyswietlacza', models.CharField(max_length=255)),
                ('rozdzielczosc_xk_field', models.BigIntegerField(db_column='rozdzielczosc_(xK)')),
                ('smart_tv', models.IntegerField(db_column='smart_TV')),
            ],
            options={
                'db_table': 'telewizor',
                'managed': False,
            },
        ),
    ]
